[export]
album = [ "«albumName»",]
convert_to_jpeg = true
description_template = "{descr}"
download_missing = true
edited_suffix = ""
exiftool = true
filename_template = "{original_name}"
ignore_date_modified = true
jpeg_ext = "jpg"
jpeg_quality = 1
original_suffix = ""
skip_original_if_edited = true
finder_tag_keywords = true
xattr_template = [ [ "authors", "«authors»",], [ "findercomment", "{descr}",],]
cleanup = true
update = true
overwrite = true
report = '«report»'
directory = "{/+keyword|lower[«skipTags»]}"
